import { describe,it,expect } from 'vitest'
import { AUTH_MODE,normalizeIdentity,otpRequest,otpVerification,isProfileComplete,dashboardPath,safeReturnPath,onboardingSchema,authError } from '../src/lib/auth'
import { brandVariables } from '../src/lib/brand'
describe('mode-independent authentication',()=>{
 it('defaults to email and normalizes both identities',()=>{expect(AUTH_MODE).toBe('email');expect(normalizeIdentity(' Member@Example.com ','email')).toBe('member@example.com');expect(normalizeIdentity('+91 98765 43210','phone')).toBe('+919876543210');expect(()=>normalizeIdentity('1234567890','phone')).toThrow();expect(()=>normalizeIdentity('broken','email')).toThrow()})
 it('uses the correct Supabase send and verification types',()=>{expect(otpRequest('a@example.com','email')).toEqual({email:'a@example.com'});expect(otpVerification('a@example.com','123456','email')).toEqual({email:'a@example.com',token:'123456',type:'email'});expect(otpRequest('9876543210','phone')).toEqual({phone:'+919876543210'});expect(otpVerification('9876543210','123456','phone')).toEqual({phone:'+919876543210',token:'123456',type:'sms'});expect(()=>otpVerification('a@example.com','12','email')).toThrow()})
 it('does not mistake the placeholder name for complete onboarding',()=>{expect(isProfileComplete(null)).toBe(false);expect(isProfileComplete({full_name:' New User '})).toBe(false);expect(isProfileComplete({full_name:'Anjali Rao'})).toBe(true)})
 it('routes all roles and rejects unsafe return paths',()=>{expect(dashboardPath(null)).toBe('/no-gym');expect(dashboardPath('receptionist')).toBe('/admin');expect(dashboardPath('trainer')).toBe('/member');expect(dashboardPath(null,true)).toBe('/super-admin');for(const value of ['//evil.com','https://evil.com','/login','/onboarding','/member\\evil'])expect(safeReturnPath(value)).toBeNull();expect(safeReturnPath('/join/gym-a')).toBe('/join/gym-a')})
 it('validates optional onboarding fields without fake identities',()=>{const values={full_name:'Anjali Rao',email:'',date_of_birth:'',gender:'',emergency_contact_name:'',emergency_contact_phone:''};expect(onboardingSchema.safeParse(values).success).toBe(true);expect(onboardingSchema.safeParse({...values,date_of_birth:'2026-02-30'}).success).toBe(false);expect(onboardingSchema.safeParse({...values,date_of_birth:'2999-01-01'}).success).toBe(false);expect(onboardingSchema.safeParse({...values,emergency_contact_phone:'123'}).success).toBe(false)})
 it('provides recoverable errors and safe brand defaults',()=>{expect(authError({status:429})).toContain('wait');expect(authError({code:'otp_expired'})).toContain('expired');expect(authError({code:'PGRST202'})).toContain('Module 3 SQL');expect(brandVariables('#ffffff')['--brand-on-primary']).toBe('#000000');expect(brandVariables('red;evil')['--brand-primary']).toBe('#171717');expect(brandVariables('#000000')['--brand-primary-light']).toBe('#e6e6e6')})
})
