import { beforeAll,afterAll,describe,it,expect } from 'vitest'
import { PGlite } from '@electric-sql/pglite'
import { readFileSync } from 'node:fs'
const db=new PGlite()
const id=(n:number)=>'10000000-0000-4000-8000-'+n.toString().padStart(12,'0')
async function asRole(role:string,uid:string,sql:string){await db.exec(`SET ROLE ${role};SELECT set_config('request.jwt.claim.sub','${uid}',false);`);try{return await db.query(sql)}finally{await db.exec("RESET ROLE;SELECT set_config('request.jwt.claim.sub','',false);")}}
beforeAll(async()=>{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,phone text,email_confirmed_at timestamptz,phone_confirmed_at timestamptz,is_anonymous boolean DEFAULT false);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 GRANT USAGE ON SCHEMA auth TO authenticated,service_role;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,service_role;
 CREATE SCHEMA extensions;CREATE FUNCTION extensions.gen_random_bytes(n integer) RETURNS bytea LANGUAGE sql AS $$SELECT decode(repeat('ab',n),'hex')$$;`)
 await db.exec(readFileSync(new URL('../supabase/fitstack-v1.sql',import.meta.url),'utf8').replace('CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;',''))
 const patch=readFileSync(new URL('../supabase/fitstack-module3-auth.sql',import.meta.url),'utf8')
 await db.exec(patch);await db.exec(patch) // additive patch is re-runnable
 await db.exec(`INSERT INTO auth.users(id,email,email_confirmed_at) VALUES('${id(1)}','member@example.com',now()),('${id(2)}','owner@example.com',now()),('${id(3)}','unverified@example.com',null);
 INSERT INTO auth.users(id,phone,phone_confirmed_at) VALUES('${id(4)}','919876543210',now());
 INSERT INTO public.gyms(id,name,slug,brand_color) VALUES('${id(10)}','Gym A','gym-a','#123456'),('${id(11)}','Gym B','gym-b','#654321');`)
},30000)
afterAll(()=>db.close())
describe('Module 3 SQL access boundary',()=>{
 it('exposes only active public branding to anonymous visitors',async()=>{const result=await asRole('anon','',"SELECT * FROM public.get_join_gym('gym-a')");expect(result.rows).toHaveLength(1);expect(Object.keys(result.rows[0] as object).sort()).toEqual(['brand_color','id','logo_url','name','slug']);expect((await asRole('anon','',"SELECT * FROM public.get_join_gym('not-found')")).rows).toHaveLength(0);await expect(asRole('anon','','SELECT * FROM public.gyms')).rejects.toThrow();await expect(asRole('anon','','SELECT * FROM public.ensure_my_profile()')).rejects.toThrow()})
 it('creates only a verified caller profile, supports phone-null email accounts, and is idempotent',async()=>{const result=await asRole('authenticated',id(1),'SELECT * FROM public.ensure_my_profile()');expect(result.rows[0]).toMatchObject({id:id(1),email:'member@example.com',phone:null,full_name:'New User',is_super_admin:false});await asRole('authenticated',id(1),'SELECT * FROM public.ensure_my_profile()');await expect(asRole('authenticated',id(3),'SELECT * FROM public.ensure_my_profile()')).rejects.toThrow('verified');await expect(asRole('authenticated','','SELECT * FROM public.ensure_my_profile()')).rejects.toThrow();const phone=await asRole('authenticated',id(4),'SELECT * FROM public.ensure_my_profile()');expect(phone.rows[0]).toMatchObject({phone:'+919876543210'})})
 it('requires onboarding and forbids direct role and identity injection',async()=>{await expect(asRole('authenticated',id(1),"SELECT public.join_gym('gym-a')")).rejects.toThrow('Complete your profile');await expect(asRole('authenticated',id(1),`INSERT INTO public.gym_members(gym_id,profile_id,role) VALUES('${id(10)}','${id(1)}','owner')`)).rejects.toThrow();await expect(asRole('authenticated',id(1),`UPDATE public.profiles SET phone='+919999999999' WHERE id='${id(1)}'`)).rejects.toThrow();await asRole('authenticated',id(1),`UPDATE public.profiles SET full_name='Member One' WHERE id='${id(1)}'`);await asRole('authenticated',id(1),'SELECT * FROM public.ensure_my_profile()');expect((await db.query(`SELECT full_name FROM public.profiles WHERE id='${id(1)}'`)).rows[0]).toEqual({full_name:'Member One'})})
 it('self-joins exactly once and never creates billing or paid memberships',async()=>{await asRole('authenticated',id(1),"SELECT public.join_gym('gym-a')");await asRole('authenticated',id(1),"SELECT public.join_gym('gym-a')");const rows=await db.query(`SELECT role,is_active FROM public.gym_members WHERE profile_id='${id(1)}'`);expect(rows.rows).toEqual([{role:'member',is_active:true}]);expect((await db.query('SELECT count(*)::int AS n FROM public.memberships')).rows).toEqual([{n:0}]);const access=await asRole('authenticated',id(1),'SELECT * FROM public.get_my_gym_access()');expect(access.rows).toHaveLength(1);expect(access.rows[0]).not.toHaveProperty('qr_secret');expect((await asRole('authenticated',id(4),'SELECT * FROM public.get_my_gym_access()')).rows).toHaveLength(0)})
 it('preserves existing staff roles and never reactivates a blocked member',async()=>{await asRole('authenticated',id(2),'SELECT * FROM public.ensure_my_profile()');await asRole('authenticated',id(2),`UPDATE public.profiles SET full_name='Owner' WHERE id='${id(2)}'`);await db.exec(`INSERT INTO public.gym_members(gym_id,profile_id,role) VALUES('${id(10)}','${id(2)}','owner')`);await asRole('authenticated',id(2),"SELECT public.join_gym('gym-a')");expect((await db.query(`SELECT role FROM public.gym_members WHERE profile_id='${id(2)}'`)).rows[0]).toEqual({role:'owner'});await db.exec(`UPDATE public.gym_members SET is_active=false WHERE profile_id='${id(1)}'`);await expect(asRole('authenticated',id(1),"SELECT public.join_gym('gym-a')")).rejects.toThrow('inactive');await db.exec(`UPDATE public.gym_members SET is_active=true WHERE profile_id='${id(1)}'`)})
 it('reports an inactive gym without unlocking its business data',async()=>{await db.exec(`UPDATE public.gyms SET is_active=false WHERE id='${id(10)}'`);expect((await asRole('anon','',"SELECT * FROM public.get_join_gym('gym-a')")).rows).toHaveLength(0);await expect(asRole('authenticated',id(1),"SELECT public.join_gym('gym-a')")).rejects.toThrow('inactive');expect((await asRole('authenticated',id(1),'SELECT * FROM public.get_my_gym_access()')).rows[0]).toMatchObject({gym_id:id(10),is_active:false});expect((await asRole('authenticated',id(1),'SELECT id FROM public.gyms')).rows).toHaveLength(0);expect((await asRole('authenticated',id(2),'SELECT id FROM public.gyms')).rows).toHaveLength(1)})
})
